platform :ios,'8.0'

project 'SamplePushApp'

target 'SamplePushApp' do
#    pod 'SpotzPushSDK', :git => 'https://github.com/localz/Spotz-Push-iOS-SDK.git'
    pod 'SpotzPushSDK', :path => '../../../'
end
