platform :ios,'8.0'

source 'https://github.com/localz/Spotz-iOS-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

project 'SamplePushApp'
target 'SamplePushApp' do
    pod 'SpotzPushSDK'
end
target 'SampleNotificationServiceExtension' do
    pod 'SpotzPushSDK/Extension'
end
